spring.application.name=vplanner-dev
spring.banner.location=classpath:banner-dev.txt

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.drop-create=true


# Root logging level
logging.level.root=DEBUG

# Specific package logging
logging.level.vplanner=DEBUG

# Spring framework internals
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG

# Show SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Show Spring Security decisions
logging.level.org.springframework.security=DEBUG

# Show HTTP request/response details
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
